baseurl = "https://morinricardo.com/"
languageCode = "en-us"
title = "Ricardo's Blog"
# theme
theme = "hugo-later"
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-64070309-3"
disqusShortname = "jimmyangel"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "by Ricardo Morin"
  author = "Ricardo Morin"
  keywords = ["rikitraki", "jimmyangel"]
  avatar = "https://avatars1.githubusercontent.com/u/6842945"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"

  # Includes an icon in the footer for each username you enter
  [params.footerlinks]
    dribbble = ""
    email = ""
    facebook = ""
    flickr = ""
    github = "jimmyangel"
    instagram = ""
    linkedin = ""
    pinterest = ""
    rss = "yes" # just type anything here for a working RSS icon, make sure you set the "url" above!
    twitter = "jimmieangel"
    stackoverflow = "" # your stackoverflow profile, e.g. "users/50476/bart-kiers"
    youtube = "" # channel/<your_long_string> or user/<user-name>
    googleplus = "" # anything in your profile username that comes after plus.google.com/
